# based on https://github.com/santthosh/kafka-for-mac/blob/master/docker-compose.yml

version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 32181:32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-host
    ports:
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.94:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mothership:
      image: "mothership:0.2.0-SNAPSHOT"
      ports:
        - 8080:8080

#  bots:
#    image: "mothership-bots:0.1.0-SNAPSHOT"
#    environment:
#      KAFKA: 192.168.0.94:29092
#      API: http://mothership:8080/